version: "3.4"
services:
  analyzer:
    image: "ulriksandberg/sentimentanalyzer:4.0"
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 3
  correlation:
    image: "oskardock/correlation-service:0.1"
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
 # api:
 #   build:
 #     context: ./spark-api
 #   environment:
 #     - ASPNETCORE_URLS=http://+:5002
 #   -networks:
 #     - outside

networks:
  outside:
    external:
      name: 'host'
