version: "3.4"
services:
  analyzer:
    image: "ulriksandberg/sentimentanalyzer:4.0"
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 3
  correlation:
    image: "oskardock/correlation-service:0.1"
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
  api:
    image: "ulriksandberg/sparkfront:1.0"
    ports:
      - "5000:5000"
      - "5001:5001"
    -networks:
      - outside
    deploy:
      mode: replicated
      replicas: 3

networks:
  outside:
    external:
      name: 'host'
